# Generated by Django 4.1.9 on 2023-06-04 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_solicitudenlinea_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudenlinea',
            name='apellido',
            field=models.CharField(default='Valor predeterminado', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudenlinea',
            name='correo',
            field=models.EmailField(default='correo@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='solicitudenlinea',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 6, 1)),
        ),
        migrations.AddField(
            model_name='solicitudenlinea',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='solicitudenlinea',
            name='nombre',
            field=models.CharField(default='valor predeterminado', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
