# Generated by Django 4.1.9 on 2023-06-04 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_solicitudenlinea_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='apellido',
            field=models.CharField(blank=True, default='Valor predeterminado', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='correo',
            field=models.EmailField(blank=True, default='correo@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 1)),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='hora',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='nombre',
            field=models.CharField(blank=True, default='Valor predeterminado', max_length=100),
        ),
    ]
