# Generated by Django 4.1.9 on 2023-06-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_solicitudenlinea_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='hora',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
