# Generated by Django 4.1.9 on 2023-06-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_solicitudenlinea_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudenlinea',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
    ]
