# Generated by Django 4.1.9 on 2023-06-05 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_solicitudenlinea_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitudenlinea',
            name='tecnico_id',
        ),
        migrations.AddField(
            model_name='solicitudenlinea',
            name='servicios',
            field=models.CharField(choices=[('Opcion 1', 'Estudio de suelo'), ('Opcion 2', 'Montar y desmontar material'), ('Opcion 3', 'Mantenimiento y reparación')], default='Opcion 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='solicitudenlinea',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='controlInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fecha', models.DateField(blank=True)),
                ('hora', models.TimeField(blank=True)),
                ('estado', models.CharField(default='Pendiente', max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('tecnico_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tecnico')),
            ],
        ),
    ]
