# Generated by Django 4.1.9 on 2023-06-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historialsolicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudenlinea',
            name='tecnico_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tecnico'),
        ),
    ]
