# Generated by Django 4.1.9 on 2023-06-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_solicitudenlinea_tecnico_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudenlinea',
            name='servicios',
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Opcion 1', 'Estudio de suelo'), ('Opcion 2', 'Montar y desmontar material'), ('Opcion 3', 'Mantenimiento y reparación')], max_length=100)),
                ('otra_opcion', models.CharField(blank=True, max_length=100)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitudenlinea')),
            ],
        ),
    ]
