# Generated by Django 4.0.3 on 2023-06-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_solicitudenlinea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudenlinea',
            name='servicio',
            field=models.IntegerField(choices=[(1, 'Estudio de suelo'), (2, 'Montar y desmontar material'), (3, 'Mantenimiento y reparación')], default=1),
        ),
        migrations.DeleteModel(
            name='SolicitudServicio',
        ),
    ]
