# Generated by Django 4.1.9 on 2023-06-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_compra_usuario_alter_compra_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='servicio',
            field=models.IntegerField(choices=[(1, 'Estudio de suelo'), (2, 'Montar y desmontar material'), (3, 'Mantenimiento y reparación')], default=1),
        ),
    ]
