# Generated by Django 4.1.9 on 2023-06-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_compra_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='nombre_servicio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
