# Generated by Django 4.1.9 on 2023-06-25 23:44

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0019_compra_nombre_servicio_compra_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='controlinspeccion',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='controlinspeccion',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='controlinspeccion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='controlinspeccion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='controlinspeccion',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='controlinspeccion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='controlinspeccion',
            name='tecnico_id',
        ),
        migrations.AddField(
            model_name='controlinspeccion',
            name='Solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.solicitudenlinea'),
        ),
        migrations.AddField(
            model_name='controlinspeccion',
            name='estado2',
            field=models.CharField(default='En Proceso', max_length=100),
        ),
        migrations.CreateModel(
            name='UsuarioCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_usuariocustomizado_set', related_query_name='custom_usuariocustomizado', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_usuariocustomizado_set', related_query_name='custom_usuariocustomizado', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='controlinspeccion',
            name='equipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.equipoinspeccion'),
        ),
    ]
