# Generated by Django 4.1.9 on 2023-06-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_equipoinspeccion_remove_controlinspeccion_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlinspeccion',
            name='Solicitud_id',
        ),
        migrations.AddField(
            model_name='solicitudenlinea',
            name='controlInspeccion_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.controlinspeccion'),
        ),
        migrations.DeleteModel(
            name='UsuarioCustomizado',
        ),
    ]
