# Generated by Django 4.1.9 on 2023-06-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_controlinspeccion_solicitud_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoinspeccion',
            name='Cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipoinspeccion',
            name='disponibilidad',
            field=models.CharField(default='No Disponible', max_length=50),
        ),
    ]
